site_name: Lógica e Linguagem de Programação
site_description: Site de aulas e materiais didáticos da matéria "Lógica e Linguagem de Programação"
site_author: Luccas Alencar

# Repositório (substitua pelo seu)
repo_name: LuccasAlencar/aulas-logica-e-linguagem-de-programacao
repo_url: https://github.com/LuccasAlencar/aulas-logica-e-linguagem-de-programacao

# Tema
theme:
  name: material
  language: pt-BR
  palette:
    # Modo claro
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
    # Modo escuro
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.footer

# Plugins
plugins:
  - search:
      lang: pt

# Extensões Markdown
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Navegação
nav:
  - Home: index.md
  - Aulas:
    - Aula 1 - Introdução à estrutura básica de programação: aulas/aula1.md
    - Aula 2 - Algoritmos no cotidiano: aulas/aula2.md
    - Aula 3 - Fluxogramas e representação visual: aulas/aula3.md
    - Aula 4 - Variáveis e tipos de dados: aulas/aula4.md
    - Aula 5 - Entrada de Dados : aulas/aula5.md
    - Aula 6 — Processamento de dados: aulas/aula6.md
    - Aula 7 — Saída de dados: aulas/aula7.md
    - Aula 8 — Exercícios: aulas/aula8.md
    - Aula 9 - Condição simples- introdução ao SE: aulas/aula9.md
    - Aula 10 - Condição composta- SE…SENÃO: aulas/aula10.md
    - Aula 11 - Condições aninhadas- SE dentro de SE : aulas/aula11.md
    - Aula 12 - Exercícios práticos com decisões: aulas/aula12.md

    

extra:
  generator: false