site_name: Lógica e Linguagem de Programação
site_description: Site de aulas e materiais didáticos da matéria "Lógica e Linguagem de Programação"
site_author: Luccas Alencar

# Repositório (substitua pelo seu)
repo_name: LuccasAlencar/aulas-logica-e-linguagem-de-programacao
repo_url: https://github.com/LuccasAlencar/aulas-logica-e-linguagem-de-programacao

# Tema
theme:
  name: material
  language: pt-BR
  palette:
    # Modo claro
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
    # Modo escuro
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.footer

# Plugins
plugins:
  - search:
      lang: pt

# Extensões Markdown
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Navegação
nav:
  - Home: index.md
  - Aulas:
    - Aula 1 - O que é programar : aulas/Aula 1 - O que é programar.md
    - Aula 2 - Algoritmos no cotidiano : aulas/Aula 2 - Algoritmos no cotidiano.md
    - Aula 3 - Fluxogramas e representação visual : aulas/Aula 3 - Fluxogramas e representação visual.md
    - Aula 4 - Variáveis e tipos de dados : aulas/Aula 4 - Variáveis e tipos de dados.md
    - Aula 5 - Entrada de dados : aulas/Aula 5 - Entrada de dados.md
    - Aula 6 - Processamento de dados : aulas/Aula 6 - Processamento de dados.md
    - Aula 7 - Saída de dados : aulas/Aula 7 - Saída de dados.md
    - Aula 8 - Exercícios integrados (entrada, processamento e saída) : aulas/Aula 8 - Exercícios integrados (entrada, processamento e saída).md
    - Aula 9 - Condição simples- introdução ao SE : aulas/Aula 9 - Condição simples- introdução ao SE.md
    - Aula 10 - Condição composta- SE...SENÃO : aulas/Aula 10 - Condição composta- SE...SENÃO.md





extra:
  generator: false